### ISSUE TITLE
Disable URL scheme

### ISSUE THREAD

**Issue by alexxxnf** [libwilliam/flask-cdn#11]
Could you please provide an option to disable scheme in URLs generated by ```url_for```? Due to cache issues I would like my URLs to start with ```//``` rather than ```http://``` or ```https://```, e. g. ```//:my-cdn.tld/file.ext````

Original ```url_for``` has ```_scheme``` and ```_external``` to do that, but unfortunately these parameters don't work for the function provided by flask-cdn.

**Comment by libwilliam** [comment]
Just letting you know I will get back to you tomorrow with more information after I get to a computer. I'll make sure and get this added.

**Comment by libwilliam** [comment]
I will get this added for you but it will probably take a couple days because I want to rework some of the test code. 

In your example, is `//my-cdn.tld/file.ext` what you intended? Or do you really need `//:my-cdn.tld/file.ext`?

**Comment by alexxxnf** [comment]
Hi William,

My example is correct. What I need is called "protocol-relative URL".

**Comment by libwilliam** [comment]
Alright now I'm more confused. I thought protocol-relative URLs were '//archive.org'. Not '//.archive.org'.

**Comment by alexxxnf** [comment]
Sorry, my bad. You are absolutely right.

**Comment by alexxxnf** [comment]
I took the liberty to create a pull request for this, so you can focus on tests. Please, have a look.

**Comment by libwilliam** [comment]
I merged in your changes. Thank you!

There will be a new release out soon after I get some of my new code cleaned up a bit.

**Comment by libwilliam** [comment]
I've decided to put your changes into a v1.5.0 release. Then I'll put out a v2.0.0 release that uses protocol-relative URLs by default (when `CDN_HTTPS = None`) and another small API break that probably won't affect anyone.

**Comment by alexxxnf** [comment]
Thank you William, this is great news!
