### ISSUE TITLE
error flask.ext.cdn is deprecated

### ISSUE THREAD

**Issue by adamcooley** [libwilliam/flask-cdn#14]
Hey there following the docs on getting this setup, and getting this alert when invoking flask-cdn. Can you advise /usr/local/lib/python2.7/dist-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.cdn is deprecated, use flask_cdn instead.
  .format(x=modname), ExtDeprecationWarning

Is there a documentation bug or am i doing something wrong?

**Comment by libwilliam** [comment]
Looks like the `import flask.ext.<name>` is deprecated as of flask 0.11. You shouldn't run into any problems by changing your code to use `import flask_cdn`. I will test everything out and get the documentation updated.

Thank you for reporting this.

**Comment by adamcooley** [comment]
So just tried changing it to import flask_cdn and it fails saying module isn't callable. I'll try and dig into it more later.

**Comment by libwilliam** [comment]
I fixed the various spots that were using the deprecated import method. Everything is working on my end. Are you still having trouble?

**Comment by libwilliam** [comment]
The fix for this was included in v1.5.1.
